version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
      - APP_ID=${APP_ID}
      - INSTALLATION_ID=${INSTALLATION_ID}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5-coder:1.5b}
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    command: serve

volumes:
  ollama-data: